### ISSUE TITLE
Broken breadcrumb in OpenShift docs

### ISSUE THREAD

**Issue by gabriel-rh** [redhataccess/ascii_binder#169]
Sample content:[ https://github.com/gabriel-ocp/ocp-breadcrumbs](https://github.com/gabriel-ocp/ocp-breadcrumbs)

Sample output: https://gabriel-ocp.github.io/ocp-breadcrumbs/openshift-enterprise/main/level1/level2/level3/level3-intro.html

Note how the level 2 breadcrumb disappears when you navigate to the 3rd level

```
Name: Level 1
Dir: level1
Distros: openshift-enterprise,openshift-webscale,openshift-origin,openshift-online,openshift-dpu
Topics:
- Name: level1 intro
  File: level1-intro.adoc
- Name: level 2
  Dir: level2
  Topics:
  - Name: level2 intro
    File: level2-intro.adoc
  - Name: level 3
    Dir: level3
    Topics:
    - Name: level3 intro
      File: level3-intro.adoc
```

===================

Originally reported in:

https://issues.redhat.com/browse/OADP-443

From https://docs.openshift.com/container-platform/4.9/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.html

You can click on Backup and Restore (see screenshot) and be linked to a broken https://docs.openshift.com/container-platform/4.9/backup_and_restore/application_backup_and_restore/backup_and_restore/index.html
