### ISSUE TITLE
Enhancement request to support 4th level topics

### ISSUE THREAD

**Issue by abellotti** [redhataccess/ascii_binder#19]
This would allow for improved organization of topics and be able to expand/retract topics while looking at 3rd level topics. So supporting both File or Dir at a 3rd level should do the trick.

So the _build_cfg.yml would support the following structure:

```
Name: REST API
Dir: api
Topics:
  - Name: Examples
    Dir: examples
    Topics:
      - Name: Querying Examples
        File: queries
      - Name: Services
        Dir: services
        Topics:
           - Name: Ordering Services
             File: ordering_services
           - Name: Retiring Services
             File: retiring_services
      - Name: Automation Requests
        File: automation_requests
```

**Comment by nhr** [comment]
In working with the OpenShift docs team, we've been leery about adding support for arbitrary topic depth. AsciiBinder can be written to handle it, but your site page templates also have to know how to handle it. To say that another way - support in the utility doesn't automatically give you support when you try to generate docs.

That said, I'll tag this as an enhancement request and we can talk it over. Thanks for checking out AsciiBinder!

**Comment by r0ckarong** [comment]
This problem just led me into a 2 hour debugging session because it wouldn't build and only referenced that a "File" reference was nil. Three levels of topics are fairly common and should be supported. We have quite extensive docs for our product and it simply is not very manageable with 3 levels.

**Comment by Fryguy** [comment]
@r0ckarong Can you post the full error and stack trace if possible?  It sounds like at a minimum we should improve the error message

**Comment by r0ckarong** [comment]
```
RuntimeError: In _topic_map.yml, the directory path 'hiro-cli/issue' for topic group Issue Handling does not exist under /home/jenkins/workspace/hiro_documentation-test/label/asciidoc-buildserver at
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:364:in `validate_topic_group'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:434:in `block (2 levels) in validate_config'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:423:in `each'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:423:in `block in validate_config'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:420:in `each'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:420:in `validate_config'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:172:in `build_config'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:562:in `block in generate_docs'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:534:in `each'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:534:in `generate_docs'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/bin/asciibinder:15:in `call_generate'
    /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/bin/asciibinder:291:in `<top (required)>'
    /usr/local/bin/asciibinder:23:in `load'
    /usr/local/bin/asciibinder:23:in `<main>'.
Try --help for help.
```

This is what it failed with. The part of _topic_map.yaml that would cause this looks like this:

```
[...]
---
Name: Reference
Dir: reference
Topics:
  - Name: Reference page
    File: reference
  - Name: HIRO Graph API
    Dir: hiro-graph-api
    Topics:
      - Name: HIRO Graph API Overview
        File: index
      - Name: API Reference
        File: rest-api
      - Name: WebSocket API
        File: ws-api
      - Name: Cluster Building
        File: cluster-building
  - Name: Calendar Syntax
    File: calendar-syntax
  - Name: HIRO CLI
    Dir: hiro-cli
    Topics:
      - Name: Overview
        File: overview
      - Name: HIRO CLI Commands
        Dir: commands
        Topics:
        - Name: Issue Handling
          Dir: issue
          Topics:
            - Name: aae_getissue
              File: aae_getissue
            - Name: aae_putissue
              File: aae_putissue
            - Name: aae_resolve_issue
              File: aae_resolve_issue
        - Name: KI Handling
          Dir: knowledge-items
          Topics:
            - Name: aae_delki
              File: aae_delki
            - Name: aae_getki
              File: aae_getki
            - Name: aae_putki
              File: aae_putki
        - Name: MARS Handling
          Dir: mars
          Topics:
            - Name: aae_convertformalnode
              File: aae_convertformalnode
            - Name: aae_delnode
              File: aae_delnode
            - Name: aae_getformalnode
              File: aae_getformalnode
            - Name: aae_getnode
              File: aae_getnode
            - Name: aae_putformalnode
              File: aae_putformalnode
        - Name: Other Tools
          Dir: other
          Topics:
            - Name: aae_batch
              File: aae_batch
            - Name: aae_debug
              File: aae_debug
            - Name: aae_getschema
              File: aae_getschema
            - Name: aae_info
              File: aae_info
            - Name: aae_put_license
              File: aae_put_license
            - Name: aae_putschema
              File: aae_putschema
---
[...]
```

As you notice there are 4 levels of topics but that limitation wasn't in the official docs.
