### ISSUE TITLE
Suspicious rendering of valid yaml source with compound array items

### ISSUE THREAD

**Issue by miminar** [redhataccess/ascii_binder#48]
When rendering a valid yaml, some pieces get rendered in way suggesting invalid syntax.

Take for example this piece of code:

```yaml
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "openshift-resource-limits"
spec:
  limits:
    - type: openshift.io/Image
      max:
        storage: 1Gi <1>
    - type: openshift.io/ImageStream
      max:
        openshift.io/image-tags: 20 <2>
        openshift.io/images: 30 <3>
```

The first line of each array item (prefixed with a dash) gets rendered in red:

![Image concise notation](https://miminar.fedorapeople.org/openshift-docs/concise-notation.png).

If I change the code above like this:

```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: openshift-resource-limits
spec:
  limits:
    - 
      type: openshift.io/Image
      max:
        storage: 1Gi <1>
    - 
      type: openshift.io/ImageStream
      max:
        openshift.io/image-tags: 20 <2>
        openshift.io/images: 30 <3>
```

The output gets rendered in expected way:

![Image correct rendering](https://miminar.fedorapeople.org/openshift-docs/correct-rendering.png).

Can we have nice rendering in both cases?
