### ISSUE TITLE
AsciiBinder builds wrong branch state

### ISSUE THREAD

**Issue by r0ckarong** [redhataccess/ascii_binder#77]
We're using asciibinder with jenkins. I've lately updated to version 0.1.9 as per rubygems repo and since then ascii_binder seems to ignore the checked out branch and always builds from develop. We now have to force checkout into a single branch to get the correct contents to build. 

I can't find an official release on the repo here so I can't check changes. Was there anything changed about the logic how branches are built? We wanto to build 4 branches all correctly specified in the _distro_map.yml but for some reason this won't work anymore.

We always get the contents of develop as a result in the branch named folders in _package.

**Comment by r0ckarong** [comment]
I have several branches that represent certain version numbers. It appears that AsciiBinder is not capable of properly distinguishing between them.

I have 5.4.0, 5.4.1 and had 5.4.x (for ongoing work on that version). This is where the problem appeared first. 5.4 would not work because it's too short so we chose .x. Apparently the filter (regex?) in the background can't properly use this and falls back to the last successfully built content during packaging. This means if I have 5.4.1 and 5.4.x it will give me the contents of 5.4.1. 

I now have created a numerically different branch 5.4.2 which builds properly.

Could you please check the logic behind this?

**Comment by nhr** [comment]
Hey there - 1) can you point me to your distro map file? 2) what command are you specifically using that is giving you trouble, and what are you expecting it to do?

**Comment by r0ckarong** [comment]
The map file looked like this: 

```
---
hiro-online:
  name: HIRO
  author: HIRO Team
  site: main
  site_name: HIRO Documentation
  site_url: http://docs.hiro.arago.co/
  branches:
    develop:
      name: develop
      dir: develop
    5.4.1:
      name: 5.4.1
      dir: 5.4.1
    5.4.0:
      name: 5.4.0
      dir: 5.4.0
    5.4.x:
      name: 5.4.x
      dir: 5.4.x
hiro-5.4:
  name: HIRO
  author: HIRO Team
  site: offline
  site_name: HIRO 5.4 Documentation
  site_url: http://localhost/apps/documentation/
  branches:
    5.4.1:
      name: 5.4.1
      dir: 5.4.1
    5.4.0:
      name: 5.4.0
      dir: 5.4.0
    5.4.x:
      name: 5.4.x
      dir: 5.4.x
```
And the described effect happens if I run just the shorthand "asciibinder" on that directory. Or "asciibinder package" or "asciibinder build". All produced the wrong output for 5.4.x (actually the contents of develop).
