### ISSUE TITLE
Bug: _distro_map.yml doesn't support directores that are just numbers

### ISSUE THREAD

**Issue by bexelbie** [redhataccess/ascii_binder#92]
this fails:

```
ascii_binder:
  name: Fedora Documentation
  author: Fedora Documentation Project <docs@lists.fedoraproject.org>
  site: main
  site_name: Home
  site_url: https://docs.fedoraproject.org/
  branches:
    f26-en-US:
      name: 26
      dir: 26
```

Low priority

**Comment by Fryguy** [comment]
If you put the directory as a yaml string, will it work?  e.g.

```yaml
ascii_binder:
  name: Fedora Documentation
  author: Fedora Documentation Project <docs@lists.fedoraproject.org>
  site: main
  site_name: Home
  site_url: https://docs.fedoraproject.org/
  branches:
    f26-en-US:
      name: "26"
      dir: "26"
```
