### ISSUE TITLE
New distro parser does not allow . in distro id

### ISSUE THREAD

**Issue by r0ckarong** [redhataccess/ascii_binder#96]
I just installed 0.1.10.1 and the new distro parser gives an error 

`- Distro ID 'hiro-5.4' is not a valid string` when a period is present in the distro id.

The _distro_map.yml looks like this:

```
---
hiro-online:
  name: HIRO
  author: HIRO Team
  site: main
  site_name: HIRO Documentation
  site_url: http://docs.hiro.arago.co/
  branches:
    develop:
     name: develop
     dir: develop
hiro-5.4:
  name: HIRO
  author: HIRO Team
  site: offline
  site_name: HIRO 5.4 Documentation
  site_url: http://localhost/apps/documentation/
  branches:
    develop:
     name: develop
     dir: develop
```

The second part will not work with the new version. I have to remove the period and it's all fine.
